repository:
  name: george-probot
  description: Branch manager
  homepage: https://github.com/pjmorr/george-probot
  has_wiki: false
labels:
  - name: stale
    color: ffffff
  - name: question
    color: cc317c